ALTER TABLE users ADD COLUMN IF NOT EXISTS province VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS district VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sector   VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cell     VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS village  VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS country  VARCHAR(60) NOT NULL DEFAULT 'Rwanda';
